# Generated by Django 3.2.6 on 2021-08-25 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='phone',
            field=models.IntegerField(default=1, max_length='11'),
            preserve_default=False,
        ),
    ]
