# Generated by Django 3.2.6 on 2021-08-25 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_about_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='img',
        ),
    ]
