# Generated by Django 3.2.6 on 2021-08-25 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_remove_about_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='descript',
            field=models.CharField(max_length=500),
        ),
    ]
