# Generated by Django 3.2.6 on 2021-08-26 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_alter_about_descript'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
