# Generated by Django 3.2.6 on 2021-08-28 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_experience'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='title',
            new_name='company',
        ),
        migrations.AlterField(
            model_name='experience',
            name='end_date',
            field=models.CharField(max_length=50),
        ),
    ]
